autoload:
  punbbClasses:
    name:           "PunBB access classes"
    ext:            .php
    path:           %SF_WEB_DIR%/forums/include/
    recursive:      on

  documentsActions:
    name:           "Base documents actions"
    ext:            .php
    path:           %SF_APP_DIR%/modules/documents/actions/

  geoPHP:
    name:           "GeoPHP"
    ext:            .inc
    path:           %SF_LIB_DIR%/geoPHP/

  # override symfony default to avoid unnecessary loads
  project:
    exclude:        [model, symfony, geoPHP, password_compat]
