all:
  storage:
    class: sfSessionStorage
    param:
      session_cookie_httponly: true

cli:
  controller:
    class: sfConsoleController
  request:
    class: sfConsoleRequest
  response:
    class: sfConsoleResponse

test:
  storage:
    class: sfSessionTestStorage

#all:
#  view_cache:
#    class:                     sfSQLiteCache
#    param:
#      automaticCleaningFactor: 0
#      database:                %SF_ROOT_DIR%/cache/cache.db

#all:
#  controller:
#    class: sfFrontWebController
#
#  request:
#    class: sfWebRequest
#
#  response:
#    class: sfWebResponse
#
#  user:
#    class: myUser
#
#  storage:
#    class: sfSessionStorage
#    param:
#      session_name: symfony
#
#  view_cache:
#    class: sfFileCache
#    param:
#      automaticCleaningFactor: 0
#      cacheDir:                %SF_TEMPLATE_CACHE_DIR%
