# NB : remember filter must stay before every other filter, else, we get this strange behaviour, 
# where header shows we are identified, and homepage does not display "add outing" due to cache
rememberFilter:
  class: rememberFilter
  
rendering: ~
web_debug: ~
security:  ~

FiltersSwitchFilter:
  class: FiltersSwitchFilter

# switch between regular and mobile version of the site
# this has to be before the cache filter
MobileFilter:
  class: MobileFilter
  
# MyCacheFilter replaces the original filter to enable action caching with user's culture
# and some optimizations with homepage and portals
cache:
  class: MyCacheFilter
  param:
    condition: %SF_CACHE%

common:    ~    
flash:     ~

# MyExecutionFilter replaces the original filter to enable action caching with user's culture :execution:
execution:
  class: MyExecutionFilter
  param:
    type: execution
