homeSuccess:
  stylesheets: [-%APP_STATIC_URL%/static/css/print.css: { media: print, position: last }]

#historySuccess:
#  javascripts:    [ %APP_STATIC_URL%/static/js/diff.js ]
# does not work for historySuccess for an unknown reason
