# we do not cache partials (not worth) :
  
_association_plus:
  enabled: off

_association:
  enabled: off

_linked_routes:
  enabled: off

_summits_filter:
  enabled: off

_routes_filter:
  enabled: off

_filter_form:
  enabled: off 

_feature:
  enabled: off

filter:
  enabled: off 
