all:
  book_types:
    list:
      0:
      1: topo
      2: environment
      4: historical
      16: biography
      6: photos-art
      8: novel
      10: technics
      14: tourism
      18: magazine
  sort:
    criteria:
      'id': ID
      'bnam': name
      'act':  activities
      'auth': author
      'edit': editor
      'btyp': book_types
      'blang': langs
    filled_criteria:
      'act':
      'auth':
      'edit':
      'btyp':
      'blang':
